import pandas as pd
import json




# Charger les fichiers CSV
# dynamic_df = pd.read_csv("output/models/dynamic_clustered.csv")
# static_df = pd.read_csv("output/models/static_clustered.csv")

# # Extraire les identifiants uniques
# unique_event_ids = sorted(dynamic_df['eventId'].astype(str).unique())
# unique_clusters = sorted(set(dynamic_df['Cluster'].unique()).union(static_df['Cluster'].unique()))

# # Générer des IDs MITRE fictifs : T1000, T1001, ...
# def generate_t_id(index):
#     return f"T{1000 + index}"

# # Mapper les eventId à des techniques
# eventId_to_mitre = {eid: [generate_t_id(i)] for i, eid in enumerate(unique_event_ids)}

# # Mapper les clusters à des techniques différentes
# cluster_to_mitre = {
#     str(cluster): [generate_t_id(i + len(eventId_to_mitre))]
#     for i, cluster in enumerate(unique_clusters)
# }

# # Créer la section techniques
# techniques = {}
# all_tids = set(tid for tids in list(eventId_to_mitre.values()) + list(cluster_to_mitre.values()) for tid in tids)
# for tid in all_tids:
#     techniques[tid] = {
#         "name": f"Technique {tid}",
#         "tactic": "Unknown",
#         "description": f"Autogenerated technique for {tid}",
#         "indicators": [],
#         "metadata": {
#             "phase": "Unknown",
#             "complexity": "unknown",
#             "detection_difficulty": "unknown"
#         }
#     }

# # Construire le JSON final
# mapping = {
#     "eventId_to_mitre": eventId_to_mitre,
#     "cluster_to_mitre": cluster_to_mitre,
#     "techniques": techniques
# }

# # Sauvegarder dans un fichier
# with open("mapping/mapping_mitre.json", "w", encoding="utf-8") as f:
#     json.dump(mapping, f, indent=2, ensure_ascii=False)

# print("✅ mapping_mitre.json generated successfully.")

# import pandas as pd
# import json
# import random

# def build_event_and_cluster_mapping(dynamic_csv, static_csv, mitre_json_path, output_json):
#     # Load CSVs
#     dynamic_df = pd.read_csv(dynamic_csv)
#     static_df = pd.read_csv(static_csv)

#     # Load existing mapping JSON (to get real techniques)
#     with open(mitre_json_path, 'r', encoding='utf-8') as f:
#         mitre_data = json.load(f)

#     available_techniques = list(mitre_data.get("techniques", {}).keys())
#     if not available_techniques:
#         raise ValueError("No techniques found in the existing mapping JSON.")

#     # Build eventId_to_mitre mapping
#     event_ids = dynamic_df['eventId'].unique()
#     eventId_to_mitre = {
#         str(eid): random.sample(available_techniques, k=random.randint(1, 2))
#         for eid in event_ids
#     }

#     # Build cluster_to_mitre mapping (combine clusters from both files)
#     all_clusters = pd.concat([dynamic_df['Cluster'], static_df['Cluster']]).unique()
#     cluster_to_mitre = {
#         str(cluster): random.sample(available_techniques, k=random.randint(1, 3))
#         for cluster in all_clusters
#     }

#     # Final structure
#     final_mapping = {
#         "eventId_to_mitre": eventId_to_mitre,
#         "cluster_to_mitre": cluster_to_mitre,
#         "techniques": mitre_data["techniques"]  # keep existing
#     }

#     # Save to file
#     with open(output_json, 'w', encoding='utf-8') as f:
#         json.dump(final_mapping, f, indent=4)

#     print(f"✅ Updated mapping saved to: {output_json}")

# # --- Example usage
# build_event_and_cluster_mapping(
#     dynamic_csv='output/models/dynamic_clustered.csv',
#     static_csv='output/models/static_clustered.csv',
#     mitre_json_path='mapping/mapping_mitre.json',
#     output_json='mapping/mapping_mitre_final.json'
# )

#regroupement auto de Evenid et cluster

# import pandas as pd
# import json


# from collections import defaultdict
# from src.logger import logger

# def generate_cluster_to_mitre(dynamic_file, mapping_file):
#     # Load dynamic dataset
#     df = pd.read_csv(dynamic_file)
#     df['eventId'] = df['eventId'].astype(str)
#     df['Cluster'] = df['Cluster'].astype(str)

#     logger.info("Loaded dynamic data for MITRE mapping generation.")

#     # Load existing mapping file
#     with open(mapping_file, 'r', encoding='utf-8') as f:
#         mapping = json.load(f)

#     eventid_to_mitre = mapping.get("eventId_to_mitre", {})
#     cluster_to_mitre = defaultdict(set)

#     # Generate mapping cluster -> list of techniques
#     for _, row in df.iterrows():
#         eid = row['eventId']
#         cluster = row['Cluster']
#         techniques = eventid_to_mitre.get(eid, [])
#         cluster_to_mitre[cluster].update(techniques)

#     # Convert sets to sorted lists
#     cluster_to_mitre = {k: sorted(list(v)) for k, v in cluster_to_mitre.items()}

#     # Inject into mapping and save
#     mapping['cluster_to_mitre'] = cluster_to_mitre

#     with open(mapping_file, 'w', encoding='utf-8') as f:
#         json.dump(mapping, f, indent=2)

#     logger.info("cluster_to_mitre successfully generated and updated in mapping file.")

# if __name__ == "__main__":
#     dynamic_path = "output/models/dynamic_clustered.csv"
#     mapping_path = "mapping/mapping_mitre.json"
#     generate_cluster_to_mitre(dynamic_path, mapping_path)

#format de donnée

# import csv
# import json

# # Fonction pour transformer chaque ligne en un format texte pour BERT
# def create_text(row):
#     timestamp = row['timestamp']
#     process_id = row['processId']
#     thread_id = row['threadId']
#     mitre_techniques = row['MITRE_Techniques']
    
#     # Créer une description textuelle pour l'événement
#     text = f"L'événement avec le timestamp {timestamp} indique un comportement. Le processus avec ID {process_id} et thread ID {thread_id} a exécuté les techniques MITRE suivantes : {mitre_techniques}."
#     return text

# # Ouvrir ton fichier CSV
# input_file = r'C:\Users\nguey\OneDrive\Documents\UY1\Articles\innovsecu\output\dynamic_mitre_mapped.csv'
# output_file = r'C:\Users\nguey\OneDrive\Documents\UY1\Articles\innovsecu\output\dynamic_mitre_mapped.json'


# # Lecture du fichier CSV et création du JSON
# data = []
# with open(input_file, newline='', encoding='utf-8') as csvfile:
#     reader = csv.DictReader(csvfile)
    
#     for row in reader:
#         text = create_text(row)
#         label = "malveillant" if row['Benign'] == '0' else "bénin"  # Classification binaire
#         data.append({"text": text, "label": label})

# # Sauvegarder dans un fichier JSON
# with open(output_file, 'w', encoding='utf-8') as jsonfile:
#     json.dump({"data": data}, jsonfile, ensure_ascii=False, indent=4)

# print(f"Fichier JSON créé avec succès : {output_file}")


# import csv
# import json

# # Fonction pour transformer chaque ligne en un format texte pour BERT
# def create_text(row):
#     timestamp = row['timestamp']
#     process_id = row['processId']
#     thread_id = row['threadId']
#     mitre_techniques = row['MITRE_Techniques']
    
#     # Créer une description textuelle pour l'événement
#     text = f"L'événement avec le timestamp {timestamp} indique un comportement. Le processus avec ID {process_id} et thread ID {thread_id} a exécuté les techniques MITRE suivantes : {mitre_techniques}."
#     return text

# # Lire le fichier static_clustered.csv et stocker les labels Benign dans un dictionnaire
# static_file = r'C:/Users/nguey/OneDrive/Documents/UY1/Articles/innovsecu/output/models/static_clustered.csv'
# benign_labels = {}

# with open(static_file, newline='', encoding='utf-8') as static_csv:
#     reader = csv.DictReader(static_csv)
#     for row in reader:
#         benign_labels[row['Cluster']] = row['Benign']

# # Ouvrir le fichier dynamic_clustered.csv
# input_file = r'C:/Users/nguey/OneDrive/Documents/UY1/Articles/innovsecu/output/dynamic_mitre_mapped.csv'
# output_file = r'C:/Users/nguey/OneDrive/Documents/UY1/Articles/innovsecu/output/dynamic_mitre_mapped_with_labels.json'

# # Lecture du fichier dynamique et ajout des labels Benign
# data = []
# with open(input_file, newline='', encoding='utf-8') as csvfile:
#     reader = csv.DictReader(csvfile)
    
#     for row in reader:
#         cluster = row['Cluster']  # On suppose que 'Cluster' est la clé pour fusionner les deux fichiers
#         benign_label = benign_labels.get(cluster, 'Unknown')  # 'Unknown' si pas de correspondance
        
#         # Créer une description textuelle pour BERT
#         text = create_text(row)
        
#         # Labeler l'événement comme malveillant ou bénin
#         label = "malveillant" if benign_label == '0' else "bénin" if benign_label == '1' else "inconnu"
        
#         data.append({"text": text, "label": label})

# # Sauvegarder dans un fichier JSON
# with open(output_file, 'w', encoding='utf-8') as jsonfile:
#     json.dump({"data": data}, jsonfile, ensure_ascii=False, indent=4)

# print(f"Fichier JSON créé avec succès : {output_file}")

#téléchargment du model BERT
# from transformers import BertTokenizer, BertForSequenceClassification

# print("📦 Téléchargement du tokenizer BERT...")
# tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

# print("📥 Téléchargement du modèle BERT...")
# model = BertForSequenceClassification.from_pretrained("bert-base-uncased")

# print("💾 Sauvegarde dans ./bert_model...")
# tokenizer.save_pretrained("./bert_model")
# model.save_pretrained("./bert_model")

# print("✅ Modèle et tokenizer BERT téléchargés et sauvegardés localement.")

# split_tokenized_data.py
import torch
import os
from sklearn.model_selection import train_test_split

# Chemin d'entrée
input_path = "output/tokenized_data.pt"
train_output = "output/train_data.pt"
val_output = "output/validation_data.pt"

print("📦 Chargement des données complètes...")
data = torch.load(input_path)

input_ids = data["input_ids"]
attention_mask = data["attention_mask"]
labels = data["labels"]

# Séparation
print("✂️ Séparation des données en train/val...")
train_idx, val_idx = train_test_split(range(len(labels)), test_size=0.1, random_state=42)

train_data = {
    "input_ids": [input_ids[i] for i in train_idx],
    "attention_mask": [attention_mask[i] for i in train_idx],
    "labels": [labels[i] for i in train_idx],
}

val_data = {
    "input_ids": [input_ids[i] for i in val_idx],
    "attention_mask": [attention_mask[i] for i in val_idx],
    "labels": [labels[i] for i in val_idx],
}

torch.save(train_data, train_output)
torch.save(val_data, val_output)

print("✅ Données sauvegardées :")
print(f"   - Entraînement : {train_output}")
print(f"   - Validation : {val_output}")




